/* ====================================================================
   THE SKILL MARKET  ·  skillmarketcap, resurrected inside Company University
   --------------------------------------------------------------------
   /board ranks COMPANIES (the supply of jobs and schools).
   /skills ranks the most in-demand SKILLS (the demand).
   The certification is the bridge: it matches talent to demand, the way
   myequation.in routes learners through projects into hiring.

   Data is grounded in 2026 labor-market research. The seed rows below are
   replaced wholesale by the researched dataset. House style: no em dashes.
==================================================================== */

export type Growth = "surging" | "hot" | "steady" | "cooling";
export type TalentGap = "severe" | "moderate" | "balanced";

export interface SkillRow {
  name: string;
  domain: string;
  oneLine: string;
  demandSignal: string; // real evidence, e.g. "US postings +34% YoY"
  salary: string; // US total-comp range, e.g. "$140k-210k"
  growth: Growth;
  cert: string; // the single most respected certification / course
  certProvider: string;
  gap: TalentGap; // talent scarcity = how valuable a match is
}

/* Demand "market cap": a 0-100 index from growth + talent gap + pay.
   Deliberately simple and legible. The point is the ranking, not false
   precision. Refine the weights as the research firms up. */
const GROWTH_W: Record<Growth, number> = { surging: 38, hot: 28, steady: 16, cooling: 5 };
const GAP_W: Record<TalentGap, number> = { severe: 32, moderate: 20, balanced: 8 };

function payPoints(salary: string): number {
  // Continuous, from the top of the comp range (in $k), so pay differentiates
  // skills that otherwise tie on growth and scarcity. Capped at 30.
  // 30 <= n < 1000 keeps $k comp figures and drops stray years like 2024/2025.
  const nums = (salary.match(/\d+/g) ?? []).map(Number).filter((n) => n >= 30 && n < 1000);
  const topK = nums.length ? Math.max(...nums) : 0;
  return Math.min(30, Math.round(topK / 13));
}

export function demandScore(s: SkillRow): number {
  return Math.min(100, GROWTH_W[s.growth] + GAP_W[s.gap] + payPoints(s.salary));
}

export function tier(score: number): "S" | "A" | "B" | "C" {
  if (score >= 80) return "S";
  if (score >= 64) return "A";
  if (score >= 48) return "B";
  return "C";
}

export function ranked(rows: SkillRow[] = skills): SkillRow[] {
  return [...rows].sort((a, b) => demandScore(b) - demandScore(a));
}

/* Grounded in 2026 labor-market research (LinkedIn, Stanford AI Index,
   WEF Future of Jobs, BLS, salary guides). 82 skills across 12 domains.
   Regenerate from the skill-market-research workflow. */
export const skills: SkillRow[] = [
  {
    name: "LLM / RAG engineering",
    domain: "AI / GenAI",
    oneLine: "Building production apps on LLMs with retrieval-augmented generation over private data",
    demandSignal: "LinkedIn 2026 names AI engineering the #1 fastest-growing skill; RAG and LangChain are the top-cited AI-engineer skills; ML/AI engineer roles grew ~41.8% YoY (Q1 2026)",
    salary: "$160k-310k",
    growth: "surging",
    cert: "Generative AI with LLMs",
    certProvider: "DeepLearning.AI (Andrew Ng, on Coursera)",
    gap: "severe",
  },
  {
    name: "Agentic AI / AI agent engineering",
    domain: "AI / GenAI",
    oneLine: "Designing autonomous multi-step agents with tool use, planning and orchestration",
    demandSignal: "Agentic AI job postings up ~280% YoY to ~90k US listings (Stanford AI Index 2026); 52% of talent leaders plan to deploy agents by end-2026, 88% of those already deployed are raising budgets (Korn Ferry)",
    salary: "$185k-320k",
    growth: "surging",
    cert: "Building RAG Agents with LLMs",
    certProvider: "NVIDIA Deep Learning Institute",
    gap: "severe",
  },
  {
    name: "MLOps / ML platform engineering",
    domain: "AI / GenAI",
    oneLine: "Deploying, serving, monitoring and scaling ML and LLM models in production",
    demandSignal: "Flagged as one of the three most severe shortages (demand >85/100, supply <35/100); comp jumped ~20% YoY through 2025; MLOps skills add a 25-40% base premium",
    salary: "$130k-257k",
    growth: "hot",
    cert: "Professional Machine Learning Engineer",
    certProvider: "Google Cloud",
    gap: "severe",
  },
  {
    name: "LLM fine-tuning & model training",
    domain: "AI / GenAI",
    oneLine: "Adapting and training foundation models via fine-tuning, RLHF and evaluation",
    demandSignal: "Cited as the single highest-paid technical AI skill; frontier labs (OpenAI, Anthropic, xAI) pay $300k+ base for it; fewer than 1 in 4 ML engineers has hands-on production fine-tuning experience",
    salary: "$220k-350k",
    growth: "surging",
    cert: "Deep Learning Specialization",
    certProvider: "DeepLearning.AI (Coursera)",
    gap: "severe",
  },
  {
    name: "AWS/Azure ML cloud deployment",
    domain: "AI / GenAI",
    oneLine: "Building and shipping ML/GenAI workloads on major cloud ML platforms",
    demandSignal: "AWS ML Specialty and Google Pro ML Engineer are the most-listed AI certs in job postings, correlating with ~20-25% pay bumps; SageMaker/Vertex named core to operationalizing AI",
    salary: "$140k-230k",
    growth: "hot",
    cert: "Certified Machine Learning Engineer - Associate",
    certProvider: "Amazon Web Services (AWS)",
    gap: "moderate",
  },
  {
    name: "PyTorch & deep learning engineering",
    domain: "AI / GenAI",
    oneLine: "Building and training neural nets in PyTorch across vision, NLP and multimodal",
    demandSignal: "PyTorch, deep learning and computer vision are the top-cited skills for ML researchers per LinkedIn 2026; foundational across nearly all frontier and applied AI roles",
    salary: "$150k-300k",
    growth: "steady",
    cert: "Deep Learning Specialization",
    certProvider: "DeepLearning.AI (Coursera)",
    gap: "moderate",
  },
  {
    name: "Prompt engineering & AI literacy",
    domain: "AI / GenAI",
    oneLine: "Reliably steering LLMs and applying AI tools across business workflows",
    demandSignal: "AI literacy job postings +70% YoY and up 6x share of listings; prompt-engineering profile mentions +177% since 2023; AI-skilled workers earn a ~56% wage premium (PwC 2026)",
    salary: "$90k-180k",
    growth: "hot",
    cert: "ChatGPT Prompt Engineering for Developers",
    certProvider: "DeepLearning.AI (with OpenAI)",
    gap: "moderate",
  },
  {
    name: "Analytics Engineering (dbt + SQL + data modeling)",
    domain: "Data",
    oneLine: "Owning the transformation layer that turns raw data into trusted models",
    demandSignal: "dbt is the de facto transformation standard; recruitingfromscratch analysis of 1.9M postings puts median analytics-engineer base near $158k, and dbt Labs' 2026 State of Analytics Engineering report shows the role now enterprise-embedded and AI-adjacent",
    salary: "$115k-$190k",
    growth: "hot",
    cert: "dbt Analytics Engineering Certification",
    certProvider: "dbt Labs",
    gap: "severe",
  },
  {
    name: "Cloud data platform engineering (Snowflake / Databricks / Spark)",
    domain: "Data",
    oneLine: "Building pipelines and lakehouses on modern cloud data platforms",
    demandSignal: "Spark dominant at ~39% of DE postings, Snowflake ~29%, Databricks ~17%; recruitingfromscratch reports 2026 median DE salary ~$185k with platform specialists commanding a 20-40% premium over generalists",
    salary: "$127k-$210k",
    growth: "hot",
    cert: "SnowPro Core (COF-C03) / Databricks Certified Data Engineer Associate",
    certProvider: "Snowflake / Databricks",
    gap: "moderate",
  },
  {
    name: "Real-time / streaming data engineering (Kafka + Flink)",
    domain: "Data",
    oneLine: "Building low-latency streaming pipelines and stateful stream processing",
    demandSignal: "Kai Waehner's 2026 streaming landscape shows Kafka+Flink evolving into full platforms; Kafka and Databricks roles push senior salaries above $200k in SF/Seattle/NYC per recruitingfromscratch",
    salary: "$140k-$215k",
    growth: "hot",
    cert: "Confluent Certified Developer for Apache Kafka (CCDAK)",
    certProvider: "Confluent",
    gap: "severe",
  },
  {
    name: "Data governance, quality & observability",
    domain: "Data",
    oneLine: "Cataloging, lineage, quality, and access controls to make data AI-ready",
    demandSignal: "Spectraforce and USDSI cite governance implementation as a top hard-to-fill DE competency because it now bundles with architecture and AI integration; WEF Future of Jobs projects ~100% growth in big-data-specialist demand 2025-2030",
    salary: "$120k-$185k",
    growth: "steady",
    cert: "CDMP (Certified Data Management Professional)",
    certProvider: "DAMA International",
    gap: "moderate",
  },
  {
    name: "Python + SQL data science foundation with statistics/ML",
    domain: "Data",
    oneLine: "Core analysis, modeling, and experimentation on business data",
    demandSignal: "Python appears in ~70% and SQL in ~69% of DE postings; NLP demand in postings jumped from 5% to 19% in under a year per cobloom/365 Data Science; LinkedIn 2026 shows AI-literacy postings up 70%+ YoY",
    salary: "$110k-$180k",
    growth: "steady",
    cert: "AWS Certified Data Engineer - Associate",
    certProvider: "Amazon Web Services",
    gap: "moderate",
  },
  {
    name: "Kubernetes / cloud-native container orchestration",
    domain: "Cloud / DevOps",
    oneLine: "Operating containerized apps at scale with Kubernetes as the default runtime",
    demandSignal: "Indeed lists ~33,800 US jobs requiring Kubernetes; CNCF reports 80%+ of orgs run it in production and CKA exam enrollments hit ~291k in 2025 (+16% YoY)",
    salary: "$135k-195k",
    growth: "hot",
    cert: "Certified Kubernetes Administrator (CKA)",
    certProvider: "The Linux Foundation / CNCF",
    gap: "severe",
  },
  {
    name: "Platform engineering / Internal Developer Platforms (IDP)",
    domain: "Cloud / DevOps",
    oneLine: "Building self-service internal platforms so developers ship faster and safer",
    demandSignal: "Gartner projects 80% of large software orgs will have platform teams by 2026 (up from 45% in 2022, ~55% in 2025); mid-market enterprises now staffing these teams",
    salary: "$150k-275k",
    growth: "surging",
    cert: "Kubestronaut / CNCF cloud-native credential stack (CKA + CKAD + CKS)",
    certProvider: "CNCF / The Linux Foundation",
    gap: "severe",
  },
  {
    name: "Infrastructure as Code (Terraform / OpenTofu)",
    domain: "Cloud / DevOps",
    oneLine: "Provisioning and versioning cloud infrastructure declaratively in code",
    demandSignal: "~710 Indeed and ~300 ZipRecruiter US roles explicitly require Terraform Associate cert; ~80% of IaC-adopting orgs use Terraform, now a baseline expectation even in non-DevOps roles",
    salary: "$120k-175k",
    growth: "steady",
    cert: "HashiCorp Certified: Terraform Associate",
    certProvider: "HashiCorp",
    gap: "moderate",
  },
  {
    name: "Site Reliability Engineering (SLOs, error budgets, incident response)",
    domain: "Cloud / DevOps",
    oneLine: "Applying software engineering to keep systems reliable at scale",
    demandSignal: "Robert Half 2026 guide ranges $114k-170k; 71% of tech leaders report skills-shortage project delays and senior SRE searches routinely exceed 90 days to fill",
    salary: "$130k-210k",
    growth: "hot",
    cert: "Google / Coursera SRE and DevOps Certificate (site reliability track)",
    certProvider: "Google (Coursera)",
    gap: "severe",
  },
  {
    name: "DevSecOps / cloud security engineering (shift-left, container scanning)",
    domain: "Cloud / DevOps",
    oneLine: "Embedding automated security controls into every stage of delivery",
    demandSignal: "AWS Security Specialty demand surged ~73% in one year; 36% of companies report cloud-security skills gaps with 4-6 month time-to-fill even with active recruiting",
    salary: "$130k-210k",
    growth: "surging",
    cert: "AWS Certified Security - Specialty",
    certProvider: "Amazon Web Services",
    gap: "severe",
  },
  {
    name: "Observability engineering (OpenTelemetry, Prometheus, Grafana)",
    domain: "Cloud / DevOps",
    oneLine: "Instrumenting systems with metrics, traces and logs for production insight",
    demandSignal: "Glassdoor 2026 average ~$162k; the OpenTelemetry + Prometheus + Grafana + Datadog stack is a standard requirement in SRE and platform postings; dedicated o11y job boards show hundreds of open roles",
    salary: "$133k-200k",
    growth: "hot",
    cert: "Prometheus Certified Associate (PCA)",
    certProvider: "CNCF / The Linux Foundation",
    gap: "moderate",
  },
  {
    name: "FinOps / cloud cost optimization (incl. AI/GPU spend)",
    domain: "Cloud / DevOps",
    oneLine: "Managing and optimizing cloud and GPU spend against business value",
    demandSignal: "FinOps Foundation State of FinOps tracks steady YoY adoption growth; rising GPU/AI inference costs drive demand while FOCP-certified practitioners with proven savings stay in short supply",
    salary: "$100k-215k",
    growth: "surging",
    cert: "FinOps Certified Practitioner (FOCP)",
    certProvider: "FinOps Foundation",
    gap: "moderate",
  },
  {
    name: "Cloud Security Engineering (AWS / Azure / GCP)",
    domain: "Security",
    oneLine: "Securing cloud infrastructure, workloads, and configurations across major public cloud platforms",
    demandSignal: "ISC2 2025 Workforce Study ranks cloud security the #2 skills gap at 30%; Robert Half found 41% of tech leaders will pay more for cloud security skills; CCSP job postings up 35% YoY",
    salary: "$145k-200k typical, senior/principal $220k-400k+ at large tech",
    growth: "surging",
    cert: "CCSP (Certified Cloud Security Professional)",
    certProvider: "ISC2",
    gap: "severe",
  },
  {
    name: "AI / LLM Security (adversarial ML, prompt injection defense)",
    domain: "Security",
    oneLine: "Securing AI models and pipelines against prompt injection and adversarial attacks",
    demandSignal: "ISC2 ranks AI the #1 skills gap at 34%; WEF Global Cybersecurity Outlook 2026 says 87% cite AI vulnerabilities as fastest-growing risk; 64%+ of 2026 listings require AI/ML/automation skills",
    salary: "$152k-230k, lead architects $200k-280k+, staff/principal $450k+",
    growth: "surging",
    cert: "Certified AI Security Professional (CAISP)",
    certProvider: "Practical DevSecOps",
    gap: "severe",
  },
  {
    name: "Offensive Security / Penetration Testing (red teaming)",
    domain: "Security",
    oneLine: "Hands-on exploitation and red-team validation of systems, networks, and applications",
    demandSignal: "~755 open US roles explicitly requiring OSCP; compliance frameworks (PCI DSS, FedRAMP, DoD) mandate red-team validation; OSCP scarcity acts as a hiring differentiator",
    salary: "$96k-158k for OSCP-tagged roles; senior red team $200k+ base plus bonus/equity",
    growth: "hot",
    cert: "OSCP (Offensive Security Certified Professional)",
    certProvider: "OffSec",
    gap: "moderate",
  },
  {
    name: "GRC (Governance, Risk & Compliance)",
    domain: "Security",
    oneLine: "Managing security frameworks, audits, risk registers, and regulatory compliance programs",
    demandSignal: "Info security analyst roles projected +32% through 2032; CISM appears in ~65% of CISO postings; CISSP/CISM/CRISC routinely required; Big 4 actively recruit for advisory practices",
    salary: "$97k-115k analyst; senior $115k-195k; CISM+CISSP combo $170k+",
    growth: "steady",
    cert: "CISM (Certified Information Security Manager)",
    certProvider: "ISACA",
    gap: "moderate",
  },
  {
    name: "SOC / Detection Engineering (SIEM, threat detection)",
    domain: "Security",
    oneLine: "Building detections, tuning SIEM, and hunting threats in security operations centers",
    demandSignal: "SIEM expertise appears in 78% of SOC postings (most-requested technical skill); BLS projects +29% info-sec-analyst growth through 2034 (~16k openings/yr); Tier-3 detection engineering fastest-growing cleared cyber role at NSA/DISA",
    salary: "$70k-120k (Tier 1-2); detection engineers / Tier 3 $110k-175k",
    growth: "hot",
    cert: "GCDA / GIAC Certified Detection Analyst",
    certProvider: "GIAC (SANS)",
    gap: "moderate",
  },
  {
    name: "Identity & Access Management / Zero Trust (Okta, Entra)",
    domain: "Security",
    oneLine: "Designing identity, access controls, and zero-trust architecture across enterprise platforms",
    demandSignal: "Postings frequently require hands-on Okta and Entra/AD; zero-trust flagged as a high-demand specialization that distinguishes IAM pros; central to cloud security strategies enterprise-wide",
    salary: "$107k-171k typical; senior/architect roles higher",
    growth: "steady",
    cert: "CIAM / Certified Identity and Access Manager",
    certProvider: "Identity Management Institute",
    gap: "moderate",
  },
  {
    name: "Security Scripting & Automation (Python, PowerShell, IaC)",
    domain: "Security",
    oneLine: "Automating detection, response, log analysis, and tooling with code",
    demandSignal: "Named a core cybersecurity skill in 2026 hiring guides; 64%+ of 2026 job listings require AI, ML, or automation skills; foundational across SOC, cloud, and offensive roles",
    salary: "$110k-160k as a force multiplier on security engineering roles",
    growth: "hot",
    cert: "GIAC Python Coder (GPYC)",
    certProvider: "GIAC (SANS)",
    gap: "moderate",
  },
  {
    name: "Distributed systems & system design (scalable, fault-tolerant architecture)",
    domain: "Software",
    oneLine: "Design resilient services that scale, tolerate partial failure, and reason about tradeoffs",
    demandSignal: "The system-design round is the gating filter for senior/staff backend roles in 2026; KORE1 reports 17-day time-to-fill for senior backend/infra roles but system design is where warm pipelines go cold. Employers now expect staff-level architectural fluency at every level, with cost reasoning, failure recovery, and operational maturity explicitly scored.",
    salary: "$180k-320k+ (senior to staff total comp; Levels.fyi backend median ~$194k, 75th pct ~$277k)",
    growth: "hot",
    cert: "Grokking the Modern System Design Interview (course, not a formal cert; the credential here is demonstrated design judgment)",
    certProvider: "Educative / DesignGurus",
    gap: "severe",
  },
  {
    name: "Go (Golang) for cloud-native backend & microservices",
    domain: "Software",
    oneLine: "Build high-throughput backend services and infrastructure tooling at the cloud boundary",
    demandSignal: "Go job postings grew roughly +41% in 2025, outpacing Python and Java; Go now serves ~12% of all API calls on the internet (Cloudflare Radar, up from 8.4%). The entire cloud-native toolchain (Kubernetes, Docker, Terraform, Prometheus, Grafana) is written in Go, concentrating demand at the infra boundary.",
    salary: "$150k-230k base for mid-to-senior; total comp reaches $172k+ average, up to ~$275k",
    growth: "surging",
    cert: "No dominant formal cert; the recognized credential is shipped production Go plus contributions (a Go-focused bootcamp/course substitutes weakly)",
    certProvider: "The Go team / Ardan Labs (Ultimate Go)",
    gap: "severe",
  },
  {
    name: "Kubernetes & cloud-native orchestration",
    domain: "Software",
    oneLine: "Containerize, deploy, and operate microservices on Kubernetes in production",
    demandSignal: "Demand for K8s expertise significantly exceeds supply; CKA shows up in ~54% of Kubernetes cert mentions in postings, with hundreds of roles explicitly requiring it. 60% of organizations expect a shortage of skilled cloud pros in 2026; CKA/CKAD can lift pay 15-25%.",
    salary: "$135k-190k+ (CKA holders median above $135k, senior beyond $160k; often part of a $180k+ platform-eng package)",
    growth: "hot",
    cert: "Certified Kubernetes Administrator (CKA)",
    certProvider: "CNCF / Linux Foundation",
    gap: "severe",
  },
  {
    name: "AI/LLM integration in backend (RAG, agent orchestration, model APIs)",
    domain: "Software",
    oneLine: "Wire LLMs, RAG pipelines, and agents into production request paths and APIs",
    demandSignal: "AI Engineer is the #1 fastest-growing US job title for 2026 (~143% YoY); RAG architecture appears in ~65% of applied-LLM listings and LLM demand is up ~135% YoY. Over 75% of AI-eng postings now require domain specialization, and production RAG-at-scale operators are in short supply. System-design interviews now routinely include LLM/RAG/agent components.",
    salary: "$165k-280k+ (mid-level LLM/GenAI $165k-230k; senior/staff to $280k-400k)",
    growth: "surging",
    cert: "DeepLearning.AI courses (LangChain for LLM App Dev / building RAG systems); no single dominant formal cert yet",
    certProvider: "DeepLearning.AI (Andrew Ng)",
    gap: "severe",
  },
  {
    name: "Event-driven architecture & streaming (Apache Kafka)",
    domain: "Software",
    oneLine: "Design async, event-driven systems and real-time streaming pipelines between services",
    demandSignal: "Backends are shifting from request-response to event-driven async designs; ~700+ Confluent/Kafka engineer roles listed in the US at once. Real-time data and event-driven adoption keeps demand for proven Kafka/Confluent skills high; certification is a recognized differentiator in negotiations.",
    salary: "$115k-165k for Kafka-specialist roles; higher when paired with senior distributed-systems scope ($180k+ total comp)",
    growth: "steady",
    cert: "Confluent Certified Developer for Apache Kafka (CCDAK)",
    certProvider: "Confluent",
    gap: "moderate",
  },
  {
    name: "Cloud platform engineering (AWS architecture & APIs)",
    domain: "Software",
    oneLine: "Architect and run backend systems and APIs on AWS cloud infrastructure",
    demandSignal: "The AWS Solutions Architect Associate appears in ~80% of cloud job postings; LinkedIn AWS SA postings rose from ~8,500/mo (2024) to ~10,200/mo (2026), roughly +20%. 87% of organizations report IT talent shortages, with cloud among the biggest skill gaps; AWS certs can lift pay 20-30%.",
    salary: "$147k-216k+ (SA total comp; average AWS Solutions Architect ~$176k)",
    growth: "hot",
    cert: "AWS Certified Solutions Architect - Associate (SAA-C03)",
    certProvider: "Amazon Web Services",
    gap: "moderate",
  },
  {
    name: "Site reliability engineering & observability",
    domain: "Software",
    oneLine: "Own service reliability quantitatively with SLOs, automation, and observability tooling",
    demandSignal: "Demand for people who can own reliability quantitatively remains ahead of supply as orgs adopt cloud-native, microservices, and AI-driven ops. Observability/SRE roles are actively hiring at scale; Datadog/New Relic/Prometheus expertise adds 8-15% to base, and IDP-building SREs are specifically sought to cut operational toil.",
    salary: "$130k-210k base; total comp $160k-240k mid, $240k-350k+ senior",
    growth: "hot",
    cert: "Prometheus Certified Associate (PCA) paired with a cloud/K8s cert",
    certProvider: "CNCF / Linux Foundation",
    gap: "moderate",
  },
  {
    name: "React + Next.js engineering (Server Components / App Router)",
    domain: "Web / Mobile",
    oneLine: "Building full-stack UIs with React and Next.js rendering strategies",
    demandSignal: "React is the most-used web framework in 2026 (~40% of developers); 80%+ of frontend job listings name React or Next.js explicitly",
    salary: "$120k-230k (senior US); $280k+ total comp at FAANG-level with RSUs",
    growth: "hot",
    cert: "Meta Front-End Developer Professional Certificate",
    certProvider: "Meta (via Coursera)",
    gap: "moderate",
  },
  {
    name: "TypeScript",
    domain: "Web / Mobile",
    oneLine: "Statically typed JavaScript for safer, scalable frontend and full-stack code",
    demandSignal: "Appears in ~78% of JavaScript-related job postings in 2026 (up from ~60% two years prior); 72% of frontend listings require or prefer it; GitHub's #1 language at 48.8% adoption",
    salary: "$115k-175k (baseline expectation, adds premium at senior level)",
    growth: "surging",
    cert: "Microsoft/Executive Programs TypeScript courses; official TypeScript Handbook path",
    certProvider: "Microsoft",
    gap: "moderate",
  },
  {
    name: "React Native cross-platform mobile",
    domain: "Web / Mobile",
    oneLine: "One codebase shipping native iOS and Android apps with React",
    demandSignal: "~6,400+ US LinkedIn postings, roughly 6-8x more openings than Flutter; dominant cross-platform framework by job volume in 2026",
    salary: "$125k-160k typical; median ~$122k, senior to $180k",
    growth: "steady",
    cert: "Meta React Native Specialization",
    certProvider: "Meta (via Coursera)",
    gap: "moderate",
  },
  {
    name: "Native iOS / SwiftUI development",
    domain: "Web / Mobile",
    oneLine: "Building performant native Apple apps with Swift and SwiftUI",
    demandSignal: "iOS-only candidates are the most expensive native mobile talent; senior native iOS searches close in ~17 days; BLS projects ~17% software-developer growth 2023-2033 (~140k jobs/yr)",
    salary: "$115k-155k mid-level; $155k-200k senior",
    growth: "steady",
    cert: "Apple Certified iOS Developer / App Development with Swift certification",
    certProvider: "Apple",
    gap: "moderate",
  },
  {
    name: "Web accessibility engineering (WCAG 2.2 AA / EAA compliance)",
    domain: "Web / Mobile",
    oneLine: "Making web and mobile products legally compliant and usable for everyone",
    demandSignal: "EU Accessibility Act enforceable since June 2025 (2026 first full supervision year); ADA Title II WCAG 2.1 AA deadline April 2027; 95.9% of top-million homepages fail, avg 56 WCAG failures; 77% of ADA suits hit small businesses",
    salary: "$100k-150k; specialists bill $100-150/hr",
    growth: "surging",
    cert: "IAAP Web Accessibility Specialist (WAS)",
    certProvider: "International Association of Accessibility Professionals (IAAP)",
    gap: "severe",
  },
  {
    name: "Frontend performance / Core Web Vitals (INP) engineering",
    domain: "Web / Mobile",
    oneLine: "Optimizing load, responsiveness and layout stability for rankings and revenue",
    demandSignal: "Performance engineering now a dedicated enterprise discipline; 43% of sites still fail the 200ms INP threshold (most-failed Core Web Vital); Google's vitals tie directly to search rankings and revenue",
    salary: "$106k-170k (Web Performance Engineer, avg ~$123k)",
    growth: "hot",
    cert: "Google web.dev Core Web Vitals / Lighthouse performance training",
    certProvider: "Google",
    gap: "severe",
  },
  {
    name: "AI-assisted development (Copilot/Cursor + LLM feature integration)",
    domain: "Web / Mobile",
    oneLine: "Shipping LLM-powered features and coding fluently with AI assistants",
    demandSignal: "68% of developers use AI coding assistants daily in 2026 (now a baseline skill); Cursor passed $2B ARR, Copilot at 20M+ users; employers explicitly want engineers who ship LLM-integrated features and review AI output",
    salary: "$130k-210k (premium layered on senior frontend roles)",
    growth: "surging",
    cert: "GitHub Copilot certification; Anthropic/DeepLearning.AI prompt-engineering & LLM app courses",
    certProvider: "GitHub / DeepLearning.AI",
    gap: "severe",
  },
  {
    name: "AI / LLM Product Management",
    domain: "Product",
    oneLine: "Scoping, shipping, and evaluating products built on LLMs and generative AI",
    demandSignal: "~61% of PM job postings now require AI experience; AI-PM field projected ~28% growth through 2030 (Product School, Research.com, KORE1 2026)",
    salary: "$244k-$390k (25th-75th pct total comp); $250k-$550k+ senior; $860k median at OpenAI",
    growth: "surging",
    cert: "AI Product Management Certification (Product Compass / Reforge AI PM track are the practitioner favorites; Product School AI PM Certification for career-changers)",
    certProvider: "Reforge / Product School",
    gap: "severe",
  },
  {
    name: "Growth / Experimentation PM",
    domain: "Product",
    oneLine: "Owning activation, retention, and monetization via constant product experiments",
    demandSignal: "112+ live growth-PM listings on Growth.Talent; growth/experimentation skills carry a +10% salary premium, prized at PLG companies (Growth.Talent, ProductLed, Glassdoor 2026)",
    salary: "$138k-$233k (25th-75th pct); ~$178k average total comp",
    growth: "hot",
    cert: "Reforge Growth Series (Retention + Engagement, Monetization + Pricing)",
    certProvider: "Reforge",
    gap: "moderate",
  },
  {
    name: "Product Analytics & Data Fluency",
    domain: "Product",
    oneLine: "Turning behavioral data into decisions with SQL, Amplitude, and A/B testing",
    demandSignal: "Data fluency incl. SQL carries a +12% PM salary premium; Amplitude/Mixpanel experimentation now table-stakes for data-mature teams (Amplitude, ProductLed premiums data 2026)",
    salary: "$150k-$240k total comp for analytics-heavy PM/PM-analyst roles",
    growth: "steady",
    cert: "Amplitude Analytics Certification (CAA) / Reforge Analytics for Product",
    certProvider: "Amplitude / Reforge",
    gap: "moderate",
  },
  {
    name: "AI-Assisted Product Design & Prototyping",
    domain: "Product",
    oneLine: "Designing AI products and prototyping fast with Figma Make, Cursor, and v0",
    demandSignal: "73% of hiring managers want AI-tool proficiency and 79% want candidates who can design AI products; 72% of designers now use genAI for prototyping (Figma State of Design, UX Design Institute 2026)",
    salary: "$145k-$175k base; $220k-$320k total comp senior at top tech",
    growth: "surging",
    cert: "Figma / AI-design workflow specialization (Figma AI + Cursor); Interaction Design Foundation AI-UX courses",
    certProvider: "Figma / Interaction Design Foundation",
    gap: "moderate",
  },
  {
    name: "UX Research (mixed-methods, insight-to-decision)",
    domain: "Product",
    oneLine: "Running rigorous research and turning findings into product decisions",
    demandSignal: "Cited as the single most in-demand UX role, yet dedicated research postings fell ~13% as research embeds into product roles; under 5% of firms hire junior researchers (NN/g, UX Design Institute 2026)",
    salary: "$98k-$150k base; up to ~$230k total comp senior at research-strong firms",
    growth: "steady",
    cert: "NN/g UX Certification (UX Research specialty)",
    certProvider: "Nielsen Norman Group",
    gap: "moderate",
  },
  {
    name: "Design Systems & DesignOps",
    domain: "Product",
    oneLine: "Building scalable component systems and optimizing how design teams ship",
    demandSignal: "DesignOps roles rising while generalist design demand holds (82% of leaders report flat-or-growing need, 10-25% growth); design systems flagged as a key niche opportunity (Figma survey, NN/g 2026)",
    salary: "$150k-$200k base; ~$176k senior product-designer median, higher with systems specialization",
    growth: "steady",
    cert: "NN/g UX Certification (Interaction Design / Design Systems focus)",
    certProvider: "Nielsen Norman Group",
    gap: "moderate",
  },
  {
    name: "Accessibility / Inclusive Design (WCAG)",
    domain: "Product",
    oneLine: "Making digital products WCAG-compliant and usable for everyone",
    demandSignal: "European Accessibility Act enforceable since June 2025 driving compliance hiring; market $1.42B (2025) to $3.24B (2034); 77% of orgs now fund accessibility (LevelAccess, ZipRecruiter 2026)",
    salary: "$55k-$135k for specialists; higher blended into senior product-design roles",
    growth: "hot",
    cert: "IAAP CPACC / WAS (Certified Professional in Accessibility Core Competencies)",
    certProvider: "International Association of Accessibility Professionals (IAAP)",
    gap: "severe",
  },
  {
    name: "GTM Engineering (Clay + AI outbound automation)",
    domain: "Growth",
    oneLine: "Building automated pipelines that source, enrich and message prospects with AI",
    demandSignal: "~100 net-new US job postings/month; LinkedIn calls it one of the fastest-growing GTM roles; 84% of GTM engineers use Clay as core tooling",
    salary: "$130k-260k base plus equity; median total comp ~$176k, up to ~$241k",
    growth: "surging",
    cert: "Clay Experts / Claymation certification (GTM engineering track)",
    certProvider: "Clay",
    gap: "severe",
  },
  {
    name: "Revenue Operations (RevOps)",
    domain: "Growth",
    oneLine: "Unifying sales, marketing and CS systems, data and forecasting around one funnel",
    demandSignal: "LinkedIn ranked RevOps among fastest-growing US jobs; postings up ~300% since 2020; VP RevOps title up 300% in 18 months; Gartner says 75% of high-growth firms adopt RevOps by 2026",
    salary: "$96k-160k mid; directors ~$195k, VP/CRO $180k-300k+",
    growth: "surging",
    cert: "RevOps Certification (Sales, Marketing & Platform tracks)",
    certProvider: "HubSpot Academy / RevOps Co-op",
    gap: "severe",
  },
  {
    name: "Performance Marketing / Paid Media (Meta, Google, TikTok)",
    domain: "Growth",
    oneLine: "Running pay-for-outcome ad campaigns and optimizing spend to CAC and ROAS",
    demandSignal: "LinkedIn 2026 Skills on the Rise lists performance analysis #1 and performance marketing top-10 in marketing; consistently high-volume paid-media req counts across job boards",
    salary: "Specialist ~$58k-97k; Manager ~$82k-145k, up to ~$187k (IT industry median ~$220k)",
    growth: "hot",
    cert: "Google Ads Certification (Search + PMax) / Meta Certified Media Buying Professional",
    certProvider: "Google Skillshop / Meta Blueprint",
    gap: "moderate",
  },
  {
    name: "AI-Driven Marketing (LLM workflows + prompt engineering for GTM)",
    domain: "Growth",
    oneLine: "Applying LLMs and agentic tools to produce content, ops and campaign automation",
    demandSignal: "LinkedIn 2026 ranks AI literacy #2 marketing skill; Robert Half: 37% of leaders pay more for AI/ML; applied AI in sales/marketing triggers ~43% pay bumps",
    salary: "20-43% premium over peers; senior applied-AI marketers up to ~$250k total comp",
    growth: "surging",
    cert: "AI for Marketers / Generative AI Professional certificate",
    certProvider: "Google (Google Cloud/Coursera) & LinkedIn Learning",
    gap: "severe",
  },
  {
    name: "Marketing Operations & Lifecycle Automation (Marketo/HubSpot)",
    domain: "Growth",
    oneLine: "Owning the martech stack, lead flow, nurture programs and CRM-to-MAP data",
    demandSignal: "Robert Half 2026: 33% of leaders pay more for marketing automation, among most sought-after creative/marketing hires; strong remote req volume",
    salary: "Specialist ~$70k-97k; Manager ~$95k-131k (remote automation avg ~$101k)",
    growth: "steady",
    cert: "Marketo Certified Expert (MCE) / HubSpot Marketing Software Certification",
    certProvider: "Adobe (Marketo) & HubSpot Academy",
    gap: "moderate",
  },
  {
    name: "Enterprise Sales / Complex B2B Closing (Account Executive)",
    domain: "Growth",
    oneLine: "Running multi-stakeholder deal cycles and closing large strategic SaaS accounts",
    demandSignal: "Persistent enterprise-AE demand as firms shift from volume SDR hiring to fewer high-skill closers; only ~41% of enterprise AEs hit quota, so proven closers are scarce",
    salary: "Median base ~$140k, median OTE ~$275k; top performers $400k-660k+",
    growth: "steady",
    cert: "MEDDICC / Command of the Message certification",
    certProvider: "MEDDICC.com / Force Management",
    gap: "moderate",
  },
  {
    name: "Generative Engine Optimization (GEO / AEO) + SEO",
    domain: "Growth",
    oneLine: "Structuring content so LLM search engines cite you in generated answers",
    demandSignal: "Job listings mentioning GEO / AI search / LLM visibility grew several hundred percent YoY into 2026; agencies restructuring around GEO retainers; new dedicated AI-visibility roles",
    salary: "~$70k-120k (tracks SEO/content-strategist bands; seniors command premiums, limited public data)",
    growth: "surging",
    cert: "Advanced SEO / GEO certification (AI search module)",
    certProvider: "Semrush Academy / Search Engine Land (SMX)",
    gap: "severe",
  },
  {
    name: "AI-augmented FP&A (forecasting automation and prompt/workflow skills)",
    domain: "Finance",
    oneLine: "Running planning, forecasting and scenario models with AI copilots and automation",
    demandSignal: "43% of FP&A postings now require AI/ML skills, up from 33% a year earlier; senior FP&A time-to-hire up ~20% due to thin supply of hybrid finance-plus-AI candidates",
    salary: "$85k-160k (Analyst to Manager); AI-integration roles pay 10-24% above comparable non-AI roles",
    growth: "surging",
    cert: "FP&A Professional (FPAC) certification",
    certProvider: "Association for Financial Professionals (AFP)",
    gap: "severe",
  },
  {
    name: "Financial modeling and valuation (3-statement, DCF, scenario)",
    domain: "Finance",
    oneLine: "Building integrated 3-statement, DCF and scenario models for decisions",
    demandSignal: "34% of finance leaders pay a premium specifically for financial modeling (Robert Half 2026); financial-analyst unemployment ~1.9% vs 4.2% national in early 2025",
    salary: "$74k-158k (Senior FP&A Analyst to FP&A Manager range)",
    growth: "hot",
    cert: "Financial Modeling & Valuation Analyst (FMVA)",
    certProvider: "Corporate Finance Institute (CFI)",
    gap: "moderate",
  },
  {
    name: "Finance data analytics (Power BI, SQL, Python)",
    domain: "Finance",
    oneLine: "Turning finance data into dashboards and forecasts with BI and code",
    demandSignal: "36% of finance leaders pay premium for data analytics (Robert Half 2026); 31% of controller listings now require data-analytics/AI skills, up from 25% prior year",
    salary: "$80k-130k for finance data analyst roles; higher in tech/software",
    growth: "surging",
    cert: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    certProvider: "Microsoft",
    gap: "moderate",
  },
  {
    name: "Technical accounting and financial reporting (US GAAP, ASC 606, SEC reporting)",
    domain: "Finance",
    oneLine: "Applying GAAP, revenue recognition and SEC filing rules correctly",
    demandSignal: "41% of finance leaders pay premium for financial reporting (Robert Half, the single most-paid-for skill); CPA-required roles take ~73 days to fill, 41% longer than non-CPA roles",
    salary: "$85k-160k (senior accountant to technical accounting/reporting manager)",
    growth: "hot",
    cert: "Certified Public Accountant (CPA)",
    certProvider: "AICPA / state boards of accountancy",
    gap: "severe",
  },
  {
    name: "Controllership and month-end close leadership",
    domain: "Finance",
    oneLine: "Owning the close, controls and reporting across the accounting function",
    demandSignal: "BLS projects ~124,200 annual accounting/audit openings vs ~55,000 graduates; CPA exam sitters down 30%+ since 2016; controllers among hardest roles to recruit",
    salary: "$152k-213k (Corporate Controller); Director of Finance ~$139k-195k",
    growth: "steady",
    cert: "Certified Public Accountant (CPA)",
    certProvider: "AICPA / state boards of accountancy",
    gap: "severe",
  },
  {
    name: "Management accounting and cost/profitability analysis",
    domain: "Finance",
    oneLine: "Costing, margin analysis and internal decision-support for operations",
    demandSignal: "Finance leaders prioritize skills closest to business performance and decision-making; broad accounting shortage (~300k left the profession in five years) keeps corporate finance roles hard to fill",
    salary: "$80k-140k (senior analyst to manager, corporate/management accounting)",
    growth: "steady",
    cert: "Certified Management Accountant (CMA)",
    certProvider: "Institute of Management Accountants (IMA)",
    gap: "moderate",
  },
  {
    name: "Fintech payments and financial-infrastructure engineering",
    domain: "Finance",
    oneLine: "Building payment rails, ledgers and API-based embedded-finance systems",
    demandSignal: "Payments infrastructure is a top fintech hiring priority for 2026 as real-time rails and embedded finance scale; strong demand for finance-literate engineers combining domain and cloud/API skills",
    salary: "$150k-300k+ (engineering total comp at growth/top fintech firms)",
    growth: "hot",
    cert: "AWS Certified Solutions Architect (with fintech/payments domain experience)",
    certProvider: "Amazon Web Services",
    gap: "moderate",
  },
  {
    name: "Solidity smart contract / protocol engineering",
    domain: "Web3",
    oneLine: "Writing EVM smart contracts and DeFi protocol logic in Solidity",
    demandSignal: "Solidity appears in ~40%+ of Web3 developer job postings; ~66k new Web3 roles posted in the last 12 months and ~1,249 full-stack Web3 dev openings listed on web3.career alone",
    salary: "$110k-257k base (median total-comp ~$150k-185k; senior protocol engineers at Aave/Uniswap $200k+ before token)",
    growth: "hot",
    cert: "Cyfrin Updraft SSCD+ (Solidity Smart Contract Developer)",
    certProvider: "Cyfrin Updraft",
    gap: "moderate",
  },
  {
    name: "Smart contract security auditing / research",
    domain: "Web3",
    oneLine: "Finding and fixing vulnerabilities in smart contracts before exploit",
    demandSignal: "Post-hack focus on security; demand cited as far exceeding supply, blockchain-dev demand grew ~45% in 2026 with security a top growth area; top contest auditors clear $200k-$1M+/yr in payouts plus retainers",
    salary: "$130k-280k+ (entry $70k-130k, senior/lead $180k-280k+ plus bonuses; contest earners far higher)",
    growth: "surging",
    cert: "Cyfrin CodeHawks / Updraft Smart Contract Security certification",
    certProvider: "Cyfrin",
    gap: "severe",
  },
  {
    name: "Zero-knowledge (ZK) circuit / proof engineering",
    domain: "Web3",
    oneLine: "Building ZK circuits and proofs for rollups, scaling and privacy",
    demandSignal: "Surged from niche to a top-five requirement as zkSync, StarkNet, Scroll and Polygon zkEVM hit production; described as one of the most in-demand skill sets in all of software with a tiny talent pool despite billions in ZK VC funding",
    salary: "$160k-350k+ (e.g. O(1) Labs base $201k-263k plus equity; top performers $400k+)",
    growth: "surging",
    cert: "ZK Hack / RareSkills Zero-Knowledge Proofs course",
    certProvider: "RareSkills (with ZK Hack community programs)",
    gap: "severe",
  },
  {
    name: "Rust smart contract development (Solana / non-EVM)",
    domain: "Web3",
    oneLine: "Writing Rust programs for Solana and Rust-based L1/L2 chains",
    demandSignal: "Rust is the ~2nd most-requested Web3 language (~25% of postings), driven by Solana and infrastructure; commands a premium over C/C++ due to a smaller talent pool",
    salary: "$120k-275k (Solana devs avg ~$148k-150k, range $80k-250k)",
    growth: "hot",
    cert: "Encode Club / Ackee Solana Bootcamp (Rust + Anchor)",
    certProvider: "Encode Club / Ackee Blockchain",
    gap: "moderate",
  },
  {
    name: "Full-stack dApp engineering (React/TypeScript + wagmi/viem/Foundry)",
    domain: "Web3",
    oneLine: "Connecting React and Next.js frontends to on-chain contracts",
    demandSignal: "Web3/crypto job postings grew ~78% YoY in 2025 with continued 2026 growth; Full-Stack Web3 (contracts + frontend) named a top-value skill combination; standard stack is Foundry, Hardhat, viem, wagmi, OpenZeppelin, Slither",
    salary: "$100k-200k (median blended solidity/full-stack roles ~$184k; ZipRecruiter contract $40-72/hr)",
    growth: "steady",
    cert: "Consensys Academy Blockchain Developer Bootcamp",
    certProvider: "Consensys Academy",
    gap: "balanced",
  },
  {
    name: "On-chain AI agent / autonomous protocol engineering",
    domain: "Web3",
    oneLine: "Building autonomous AI agents that transact and act on-chain",
    demandSignal: "Daily active on-chain AI agents crossed ~250k in early 2026 (+400% YoY); agentic payments on Base exceeded 100M transactions; employers now need hybrid smart-contract + AI-tooling + governance skill sets",
    salary: "$150k-300k+ (hybrid AI+crypto premium roles; scarce cross-domain talent commands top of range)",
    growth: "surging",
    cert: "Consensys/Cyfrin dev cert paired with an LLM-agent course (e.g. DeepLearning.AI agents)",
    certProvider: "Cyfrin / DeepLearning.AI",
    gap: "severe",
  },
  {
    name: "Cross-chain / interoperability & MEV engineering",
    domain: "Web3",
    oneLine: "Bridges, cross-chain messaging, and MEV searcher/builder infrastructure",
    demandSignal: "Cross-chain interoperability, protocol-level optimization and MEV cited as high-demand, high-pay areas where talent is scarce; MEV expertise reportedly adds $60k-150k to base comp; firms pay 30-50% premiums for these skills",
    salary: "$160k-350k+ (specialized infra/MEV roles at the top of the Web3 comp band)",
    growth: "hot",
    cert: "Flashbots / MEV research programs and LayerZero developer resources",
    certProvider: "Flashbots (with LayerZero dev docs/programs)",
    gap: "severe",
  },
  {
    name: "Clinical AI / medical LLM engineering (clinical decision support, ambient documentation)",
    domain: "Health tech",
    oneLine: "Building and validating LLM and ML systems for diagnosis, triage, and clinical documentation",
    demandSignal: "ManpowerGroup 2026 survey of 39,000+ employers ranks AI model/application development the hardest-to-fill skill worldwide; US AI postings hit 2.5% of all listings, up 55% YoY; over 75% of 2026 AI engineering postings now require domain specialization, with healthcare diagnostics a top named vertical; Glassdoor lists 480+ ML research-scientist-for-healthcare roles",
    salary: "$170k-$245k (enterprise health-AI; frontier-lab and staff roles exceed $300k)",
    growth: "surging",
    cert: "DeepLearning.AI / Stanford Machine Learning for Healthcare and AI in Healthcare Specialization",
    certProvider: "Coursera (Stanford / DeepLearning.AI)",
    gap: "severe",
  },
  {
    name: "FHIR / HL7 healthcare interoperability engineering",
    domain: "Health tech",
    oneLine: "Designing FHIR APIs and HL7 interfaces so clinical systems exchange data reliably",
    demandSignal: "Federal interoperability and information-blocking rules (TEFCA, CMS/ONC mandates) keep FHIR demand structurally high; ZipRecruiter shows active FHIR job market at $129k-$168k with a $161k median; multiple specialized HL7/FHIR integration roles listed across EHR vendors and health systems",
    salary: "$130k-$210k (HL7 Interface Engineer avg ~$165k)",
    growth: "hot",
    cert: "HL7 FHIR Proficiency Certification",
    certProvider: "HL7 International",
    gap: "severe",
  },
  {
    name: "Bioinformatics / NGS and single-cell genomics analysis",
    domain: "Health tech",
    oneLine: "Turning sequencing data into biological insight with pipelines in Python, R, and Linux",
    demandSignal: "CompBioJobs analyzed 1,260 bioinformatics postings cross-checked against 1,220 US DOL H1B disclosures (FY2026 Q1); employment projected ~15% growth; demand concentrated in pharma/biotech hubs (SF Bay, Boston/Cambridge, San Diego) where pay carries a 15-25% premium; single-cell (Seurat/Scanpy) and NGS pipeline skills specifically called out",
    salary: "$142k-$210k typical (Indeed avg ~$122k; principal $250k+)",
    growth: "hot",
    cert: "Genomic Data Science Specialization (Johns Hopkins)",
    certProvider: "Coursera (Johns Hopkins University)",
    gap: "moderate",
  },
  {
    name: "Real-world evidence (RWE) health data science / biostatistics",
    domain: "Health tech",
    oneLine: "Generating regulatory-grade insights from EHR, claims, and registry data using epidemiology and ML",
    demandSignal: "LinkedIn lists 11,000+ real-world-data roles in the US; FDA's expanding RWE framework for regulatory decisions drives pharma/biotech hiring; ZipRecruiter shows RWE scientist roles spanning $94k-$220k; core stack is SAS/R/Python plus EMR and claims data",
    salary: "$100k-$180k (PhD-level and pharma R&D toward $220k)",
    growth: "hot",
    cert: "SAS Certified Professional: Advanced Programming (for clinical/RWD analytics)",
    certProvider: "SAS Institute",
    gap: "moderate",
  },
  {
    name: "Clinical informatics (physician informaticist / EHR clinical decision support design)",
    domain: "Health tech",
    oneLine: "Bridging medicine and IT to design workflows, CDS, and analytics inside the EHR",
    demandSignal: "BLS projects clinical informatics specialist demand up ~28% through 2032 and health information technologists up 15% (2024-2034); 2026 marks a pivotal supply squeeze as the ABPM practice pathway closes, making the two-year ACGME fellowship the only route to physician board certification",
    salary: "$120k-$180k (physician informaticists and CMIO track significantly higher)",
    growth: "steady",
    cert: "Clinical Informatics Subspecialty Board Certification (physicians); AMIA ACHIP for non-physicians",
    certProvider: "American Board of Preventive Medicine (ABPM) / AMIA",
    gap: "severe",
  },
  {
    name: "Epic EHR application analyst / certified builder",
    domain: "Health tech",
    oneLine: "Configuring and optimizing Epic modules that run most large US health systems",
    demandSignal: "Epic's dominant US market share plus its closed certification model (training only via Epic employment or a sponsoring health system) creates persistent scarcity; experienced certified analysts (9+ yrs) reach $135k-$155k, and aging-population-driven healthcare growth sustains hiring",
    salary: "$97k-$155k (entry certified ~$52k-$65k; senior $120k-$155k)",
    growth: "steady",
    cert: "Epic Application Certification (module-specific, e.g. Epic Cogito, EpicCare)",
    certProvider: "Epic Systems (employer-sponsored only)",
    gap: "severe",
  },
  {
    name: "Healthcare cybersecurity and HIPAA data governance",
    domain: "Health tech",
    oneLine: "Securing PHI, connected medical devices, and EHR access under HIPAA and breach rules",
    demandSignal: "BLS projects 33% growth for information security analysts (2024-2034) with ~17,300 annual openings; healthcare is the #1 costliest sector for data breaches, driving demand for medical-device security and HIPAA compliance; healthcare cyber roles listed at $111k-$155k, HIPAA privacy roles $83k-$170k",
    salary: "$111k-$170k (avg US cyber ~$136k; healthcare-specialized commands a premium)",
    growth: "hot",
    cert: "HCISPP (HealthCare Information Security and Privacy Practitioner)",
    certProvider: "ISC2",
    gap: "moderate",
  },
  {
    name: "Data center / industrial electrician (high-voltage, commissioning)",
    domain: "Trades / Energy",
    oneLine: "Licensed electricians wiring and commissioning hyperscale AI data center power systems",
    demandSignal: "AI/hyperscale boom; electrical work is 45-70% of data center build cost; BLS projects 9% electrician growth 2024-2034 with ~81k openings/yr; industry cites need for 300k+ electricians for AI demand",
    salary: "$95k-165k base; $160k-260k total comp with overtime/travel in hot markets",
    growth: "surging",
    cert: "Journeyman/Master Electrician license + NCCER Electrical certification",
    certProvider: "State licensing boards + NCCER (National Center for Construction Education and Research)",
    gap: "severe",
  },
  {
    name: "Wind turbine service technician",
    domain: "Trades / Energy",
    oneLine: "Techs who climb, maintain, and repair utility-scale wind turbines and blades",
    demandSignal: "BLS ranks it the #1 fastest-growing US occupation, +49.9% employment growth 2024-2034, ~2,100 openings/yr; concentrated demand in Texas, Iowa, California",
    salary: "$49k-88k; median ~$62.6k (BLS May 2024)",
    growth: "surging",
    cert: "GWO (Global Wind Organisation) Basic Safety Training + AWEA Seal of Approval program",
    certProvider: "Global Wind Organisation (GWO); community/technical colleges (e.g. UTI, Ecotech)",
    gap: "severe",
  },
  {
    name: "Solar PV installer (photovoltaic)",
    domain: "Trades / Energy",
    oneLine: "Field techs who mount, wire, and commission rooftop and utility-scale solar arrays",
    demandSignal: "BLS projects 42% growth 2024-2034 (~8x average), ~4,100 openings/yr; 86% of solar employers report hiring difficulty",
    salary: "$39k-80k; median ~$51.9k (BLS May 2024), higher for NABCEP-certified leads",
    growth: "surging",
    cert: "NABCEP PV Installation Professional Certification",
    certProvider: "NABCEP (North American Board of Certified Energy Practitioners)",
    gap: "severe",
  },
  {
    name: "HVAC technician with heat pump specialization",
    domain: "Trades / Energy",
    oneLine: "Techs installing and servicing climate systems, especially high-growth heat pumps",
    demandSignal: "BLS projects ~8% growth 2024-2034; ~110k technicians needed; certified tech pool reportedly down ~50% over a decade; heat pump install is the highest-growth HVAC niche",
    salary: "$48k-90k; NATE certification adds a 15-20% pay premium",
    growth: "hot",
    cert: "EPA Section 608 (legally required) + NATE certification (respected voluntary credential)",
    certProvider: "US EPA (608); North American Technician Excellence (NATE)",
    gap: "severe",
  },
  {
    name: "EV charging infrastructure installer (EVSE)",
    domain: "Trades / Energy",
    oneLine: "Electricians specialized in installing and servicing EV charging stations and DC fast chargers",
    demandSignal: "US must scale from ~245k public ports to ~2.2M by 2030; NEVI rules require 25%+ of crew EVITP-certified; ~4,000 DC fast-charger ports contracted at 990 sites",
    salary: "$70k-107k+; EVITP-certified electricians report $20-40/hr wage premium",
    growth: "surging",
    cert: "EVITP (Electric Vehicle Infrastructure Training Program) certification",
    certProvider: "EVITP (national program; ~$275, ~20 hrs, valid 3 years)",
    gap: "moderate",
  },
  {
    name: "Electrical power-line installer / lineworker",
    domain: "Trades / Energy",
    oneLine: "Workers building and maintaining the transmission and distribution grid",
    demandSignal: "~$8B federal funding for 100+ transmission projects; ~103k miles of new transmission planned in 13 yrs; ~45% of experienced linemen projected to retire within a decade; ~10,700 openings/yr",
    salary: "$60k-112k; median ~$92.5k, top states (CA, HI, NY) $108k-112k",
    growth: "hot",
    cert: "DOL-registered Electrical Line Worker apprenticeship + CDL",
    certProvider: "IBEW/NECA joint apprenticeship programs; NCCER; utility-sponsored programs",
    gap: "severe",
  },
  {
    name: "Battery energy storage (BESS) field technician",
    domain: "Trades / Energy",
    oneLine: "Techs commissioning and maintaining utility-scale lithium-ion grid storage systems",
    demandSignal: "Rapid grid-storage buildout for renewable integration; acute supply-demand imbalance for utility-scale Li-ion, BMS, and interconnection experience across standalone, solar-plus-storage, and long-duration segments",
    salary: "$44k-82k technician; $98k-157k for BESS engineers; specialized commissioning roles $150k-200k+",
    growth: "surging",
    cert: "NABCEP Energy Storage Installation Professional (ESIP) + OSHA 30 / NFPA 70E",
    certProvider: "NABCEP; manufacturer programs (Tesla, Fluid/Fluence); OSHA",
    gap: "severe",
  },
];
